import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Video } from "./components/Video";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "IVAN LEZCANO | PORTFOLIO",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Video>{children}</Video> {/* Envuelve children dentro del video */}
      </body>
    </html>
  );
}